env:
  global:
    - LC_CTYPE=en_US.UTF-8
before_install:
  - wget http://dl.google.com/android/repository/android-ndk-r12-linux-x86_64.zip
  - unzip android-ndk-r12-linux-x86_64.zip
  - mv android-ndk-r12-linux-x86_64 $HOME/android-ndk
  - export NDK_ROOT=$HOME/android-ndk
  - git clone --branch cocos2d-x-3.11.1 https://github.com/cocos2d/cocos2d-x.git --recursive $HOME
cache:
  - $HOME/cocos2d-x
  - $HOME/android-ndk
matrix:
  include:
    - language: android
android:
  components:
    - android-22
script: 
  - cocos compile -p android --android-studio
