env:
  global:
    - LC_CTYPE=en_US.UTF-8
before_install:
  - mkdir $HOME/.cocos
  - cp config/local_cfg.json $HOME/.cocos
  - wget http://dl.google.com/android/repository/android-ndk-r12-linux-x86_64.zip
  - unzip android-ndk-r12-linux-x86_64.zip > /dev/null 2>&1
  - mv android-ndk-r12 $HOME/android-ndk
  - export NDK_ROOT=$HOME/android-ndk
  - git clone --branch cocos2d-x-3.11.1 --recursive https://github.com/cocos2d/cocos2d-x.git $HOME/cocos2d-x
  - export COCOS_X_ROOT=$HOME/cocos2d-x
  - export PATH=$PATH:$HOME/cocos2d-x/tools/cocos2d-console/bin
cache:
  - $HOME/cocos2d-x
  - $HOME/android-ndk
  - $HOME/.cocos
matrix:
  include:
    - language: android
android:
  components:
    - android-22
script: 
  - cocos compile -p android --android-studio
